### ISSUE TITLE
Fix usability issues

### ISSUE THREAD

**Issue by tacticiankerala** [archana77archana/Movie-Exporter#1]
We have two types of users for this application:
1. A basic user who wants to export movie details
2. An advanced user who wants to add new export format

I think the usability of the application has to be improved keeping this in mind.

For example, As a basic end user of your application the following things are confusing for me,
- Wanting to enter name of the file which has the details of the methods.
-  Wanting to type the exact full name of the input and output files/format

Similarly, each user will have different set of tasks in hand while interacting with your system. Can you try to make it easy for both the users to carry out their tasks?

**Comment by archana77archana** [comment]
I think the updated repo will make it easy for both the users. 

In the updated repo, 
- The job of the basic user is really easy. They just have to type the number of of the choice they make. They do not have to type the method name.
- For the advanced user, they can add any number of plugins they want in the Output folder. Within that plugin file, they have to create a function named printDetails() which says what the plugin is about.

Hence solving both the problems of basic and the advanced user.

**Comment by tacticiankerala** [comment]
That's great! :+1:
