### ISSUE TITLE
Use of abstract class

### ISSUE THREAD

**Issue by tacticiankerala** [archana77archana/Movie-Exporter#3]
I see that you are using abstract classes in https://github.com/archana77archana/Movie-Exporter/blob/master/src/movieexporter/MovieExporter.java. 
Could you explain why do you prefer abstract class over interface here?

**Comment by archana77archana** [comment]
- Abstract class provide the ability to define default functionality for the subclass.
- Although currently default functionality is not implemented, in the case of plugins,this can really be handy in most cases.
- For an ever evolving framework, if we introduce some new functionality, that all plugins should implement, we can just add it the base abstract class and it would be implemented in all plugins that extended it.
- In the case of interfaces, once there are some classes implementing the said interface, then if it's changed the classes that implements the same are going to be broken, here the plugins.

**Comment by tacticiankerala** [comment]
Fair enough! :+1:
